FROM nvidia/cuda:12.4.1-devel-ubuntu22.04

ENV TZ=Asia/Seoul
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app

RUN pip3 install --upgrade pip \
    && pip3 install -r requirements.txt

CMD ["python3", "audio_service.py"] 